[package]
name = "diffsol-jax"
version = "0.0.1"
edition = "2021"

[lib]
name = "diffsol_jax"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
diffsol-c = "0.4.6"
ndarray = "0.17.2"

[features]
default = ["diffsol-llvm17"]
diffsol-llvm17 = ["diffsol-c/diffsl-llvm17"]
suitesparse = ["diffsol-c/suitesparse"]

[build-dependencies]
cc = "1.0"
