[package]
name = "diffsol-jax"
version = "0.0.1"
edition = "2021"

[lib]
name = "diffsol_jax"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "stub_gen"
doc = false

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
pyo3-stub-gen = "0.8.2"
diffsol-c = "0.4.6"
ndarray = "0.17.2"

[features]
default = ["diffsol-cranelift"]
diffsol-cranelift = ["diffsol-c/diffsl-cranelift"]
diffsol-llvm17 = ["diffsol-c/diffsl-llvm17"]
suitesparse = ["diffsol-c/suitesparse"]

[build-dependencies]
cc = "1.0"
