[package]
name = "diffsol-jax"
version = "0.0.1"
edition = "2021"

[lib]
name = "diffsol_jax"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
diffsol = { version = "0.10", default-features = false, features = ["nalgebra", "diffsl-cranelift", "diffsl-llvm20", "faer"] }

[build-dependencies]
cc = "1.0"
