# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

class OdeSolver:
    def __new__(cls, diffsl_src: builtins.str) -> OdeSolver: ...
    def handle(self) -> builtins.int:
        r"""
        Stable opaque id for the inner solver, carried by the JAX FFI call.
        """

def get_ffi_capsule() -> typing.Any: ...
